### ISSUE TITLE
image name issue

### ISSUE THREAD

**Issue by Agremond** [IBM/domino-docker#36] opened 2021-02-16 14:26 UTC
I have this issue when i try to build image with traveler.
Steps to reproduce:
1. ./build.sh domino 10.0.1 FP3. Successfully
2. ./build.sh traveler 10.0.1.2. Nonsuccessfully

```
Step 1/23 : FROM hclcom/domino:latest
pull access denied for hclcom/domino, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Ok. Try to check image "hclcom/domino" in local repo.
```
docker image ls
REPOSITORY                     TAG                 IMAGE ID            CREATED             
ibmcom/domino                  10.0.1FP3           2e54485ed9cd        23 minutes ago
```
I see that image name "hclcom/domino" is not "ibmcom/domino".

Please, check image names on scripts.

**Comment by Agremond** [comment] 2021-02-16 14:31
Workaround for me is renaming images:

```
user@mstr1:~/domino-docker#docker tag ibmcom/domino:10.0.1FP3 hclcom/domino:latest
./build.sh traveler 10.0.1.2
....
Completed in 1 minute and 21 seconds
```

**Comment by Daniel-Nashed** [comment] 2021-02-17 08:42
this is the intended behavior. 
we are not tagging explicit specified versions with a latest tag by default.
there is an option to tag it as latest.

we are making sure the latest releases are all in the software.txt and set as default.
those versions are tagged with "latest" by default if you don't specify a version.

the add-on images like Traveler by default always base on the latest tagged versions.
and what you are doing isn't a work-around but the right way to do it, if you need specific versions.

you always have the option to automatically tag it latest specifying it in the build command-line.
and you could change the "from" line in the dockerfile.

we have one idea to make this more dynamic. With newer Docker versions there is a way to change the "FROM" statement in a dockerfile. That would allow us more flexible combinations without changing dockerfiles.

-- Daniel

**Comment by Agremond** [comment] 2021-02-18 11:46
You may have misunderstood me.
The problem is not that there is no "latest" tag.
The problem is that your script doesn't work out of the box. He is looking for a image with domino by non-existent image name.
```
Step 1/23 : FROM hclcom/domino:latest
pull access denied for **hclcom/domino**, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
As a result, the image for the "traveler" is not created

**Comment by Agremond** [comment] 2021-02-18 11:48
Try on a newly installed docker to download this project and build "traveler" image. You will see exactly the same error

**Comment by Daniel-Nashed** [comment] 2021-02-18 13:41
this works as intended and you have to tag or change the dockerfile as described previously.
Please re-read my previous reply.

**Comment by westteck** [comment] 2022-05-09 05:17
This is still not working, the repo hclcom/domino in dockerhub does not exist. the user hclcom in dockerhub does not exist. This is a big problem, It may work on your computer, or maybe the german dockerhub has the repo and user. I can't say why it works for you. But it does not work for me anyway. Any help would be appreciated
![Screen Shot 2022-05-08 at 10 16 16 PM](https://user-images.githubusercontent.com/6167590/167345102-4919956c-09de-422f-8e55-cf17d044c96b.png)
.

**Comment by Daniel-Nashed** [comment] 2022-05-09 05:26
Oh now I understand. You are using the `domino_container` script which is a run-time helper script to run your containers. 

There is no Docker image on Docker Hub. The GitHub repository is intended to build your Domino image on your own based on the WebKit you download from Flexnet. The script is fully automated and also points out which version to download.

We cannot publish an image on Docker Hub, because it is commercial software, we can't upload to a public repository.
Can you point out where the documentation is misleading to correct it.

The last line in the `docker_container` should not be misleading. It really says `please build image first`.
The previous output is from the Docker CLI. The last output is from our run-time script.

**Comment by Daniel-Nashed** [comment] 2022-05-09 05:47
Removed comments intended for another issue.

**Comment by Daniel-Nashed** [comment] 2022-05-09 05:48
@Agremond did you find out resolve your issue? I did not hear anything back. 

I am closing it for now. Please reopen, if you still need help.

Thanks
Daniel

**Closed as completed by Daniel-Nashed** 2022-05-09 05:48 UTC
