### ISSUE TITLE
warning durring install, still works,just fyi

### ISSUE THREAD

**Issue by westteck** [IBM/domino-docker#49] opened 2022-05-28 01:33 UTC
installing domino 12.0.1
--------------------------------------------------------------------------------

Running Domino Silent Install -- This takes a while ...

WARNING: Running Domino with a kernel at version 5 has NOT been tested by HCL!
WARNING: The operating system CentOS Stream 8 has NOT been tested by HCL!

**Comment by Daniel-Nashed** [comment] 2022-05-28 04:47
This isn't a Domino container issue. All works as intended:

- The warning messages are coming directly from the Domino installer
- The kernel is coming from your host Linux, not from the container.
- The Linux 5.3 kernel will be fully supported with Domino 12.0.2+ (12.0.2 Early Access 1 has just been released this week)
- HCL only officially tests RHEL and SLES. But other distributions are supported as long they meet kernel, glibc and libstdc++ version requirements
- The project uses CentOS Stream 9, but with the `-from=xyz` statement, you can base it on other base Linux images
- Many of them have been tested and can be referenced by their short name. For example: `-from=ubi` builds the image based on Redhat Universal Base image (the image HCL is also using for the image downloadable from Flexnet)
- The project is supporting all major distributions and versions as long they meet the minimum requirements

**Comment by Daniel-Nashed** [comment] 2022-05-28 13:53
Closing because it's not a bug and background provided.

**Closed as completed by Daniel-Nashed** 2022-05-28 13:53 UTC
